#cspell:disable
[description]
title="Sistema PV MHNV Híbrido"
building_name="Edificio Carlos Porter MHNV"
address="Calle Condell 1546"
city="Valparaíso"
tech=["PHOTOVOLTAIC"]

[location]
lat=-33.047016 
lon=-71.621509

[consumption]
cost_increment=5.5
client_id='642180-6'
measurer_id='10025437'
contract_id='BT-3 PPP'
consumption=[
        ["04-01-2023","01-02-2023",1051,97_36_1,'CLP','BT','_3','PPP'],
        ["02-02-2023","02-03-2023",1123,104_031,'CLP','BT','_3','PPP'],
        ["03-03-2023","03-04-2023",1157,107_181,'CLP','BT','_3','PPP'],
        ["04-04-2023","04-05-2023",1220,137_911,'CLP','BT','_3','PPP'],
        ["05-05-2023","01-06-2023",1299,146_841,'CLP','BT','_3','PPP'],
        ["02-06-2023","04-07-2023",1549,175_101,'CLP','BT','_3','PPP'],
        ["05-07-2023","02-08-2023",1353,152_946,'CLP','BT','_3','PPP'],
        ["03-08-2023","01-09-2023",1420,160_519,'CLP','BT','_3','PPP'],
        ["02-09-2023","03-10-2023",1283,145_033,'CLP','BT','_3','PPP'],
        ["04-10-2023","03-11-2023",1275,144_128,'CLP','BT','_3','PPP'],
        ["04-11-2023","03-12-2023",1346,152_155,'CLP','BT','_3','PPP'],
        ["04-12-2023","03-01-2024",1346,162_554,'CLP','BT','_3','PPP'],
]


[components.generator]
panel="CS 655W"
[[components.generator.input]]
description='Panel MODULO 01'
quantity=9
orientation={inc=35,az=28}
[[components.generator.input]]
description='Panel MODULO 02'
quantity=11
orientation={inc=20,az=28}
[[components.generator.input]]
description='Panel MODULO 03'
quantity=4
orientation={inc=10,az=28}

[components.process]



