"""data"""
from dataclasses import dataclass
import datetime
from enum import Enum
from econometrics import Cost
from geometry import GeoPosition, Orientation
from weather import Weather
import pandas as pd
from pandas import DataFrame


class Tech(Enum):
    """in this project will only use PV, but in the future will be expanded to other techs"""
    PHOTOVOLTAIC = 'fotovoltaico'
    SOLAR_THERMAL = 'solar térmico'


class Component:
    """each item in a project will be a component, as panels, invertor, etc"""
    def __init__(
        self,
        description:str,
        model:str = 'generic',
        specification:str|None = None,
        cost:Cost = Cost(),
        quantity:int = 1 ) -> None:
        self.description:str = description
        self.model:str = model
        self.specification:str|None = specification
        self.cost:float= cost
        self.quantity:int = quantity
    
    def total_brute_cost(self)->float:
        """cost before taxes"""
        return self.quantity*self.cost
    def total_cost_plus_taxes(self)->float:
        """cost after taxes"""
        return self.quantity*self.cost.netCost()

class Photovoltaic(Component):
    """pv panel tech"""
    energy:DataFrame = pd.DataFrame()


    def __init__(
        self, description: str,
        model: str = 'generic',
        specification: str | None = None,
        cost: Cost = Cost(),
        quantity: int = 1,
        power:int = 100,
        orientation:Orientation = Orientation()
        ) -> None:
        super().__init__(description, model, specification, cost, quantity)
        self.power = power
        self.orientation = orientation

    def normal(self)->dict[str,float]:
        """elevation and azimuth surface´s normal"""
        return {'azimuth':self.orientation.inclination,'elevation':self.orientation.inclination}

    def cos_phi(self,date:datetime,location:GeoPosition)->float:
        """or angle between sun and normal or surface"""
        # https://www.cdeep.iitb.ac.in/slides/S20/EN301/EN301-L8.pdf
            # Sun:
            # X_sun = cos(elevation_sun) * cos(azimuth_sun)
            # Y_sun = cos(elevation_sun) * sin(azimuth_sun)
            # Z_sun = sin(elevation_sun)
            # Para la normal del surface:
            # X_normal = sin(inclination_surface) * cos(azimuth_surface)
            # Y_normal = sin(inclination_surface) * sin(azimuth_surface)
            # Z_normal = cos(inclination_surface)
            # cos(θ) = X_sun * X_normal + Y_sun * Y_normal + Z_sun * Z_normal
        sun= location.sun_position(date)

        cos_phi = self.orientation.cos_phi(
            sun_azimuth=sun['azimuth'],
            sun_elevation=sun['elevation'])

        return cos_phi

    def calc_energy(self,weather:Weather):
        """calc amount of energy generated by year"""
        #fetch nasa weather data
        data = weather.get_data()
        return data
    #EOF (\n)




@dataclass
class PowerCurve:
    '''voltage curve specification'''
    max_tension:float = 30,5
    short_tension:float = 37,5
    max_ampere:float = 4,26
    short_ampere:float = 5,68


class CellType(Enum):
    """crystal cell configuration"""
    POLI = 'policristalino'
    MONO = 'monocristalino'

@dataclass
class Cell:
    '''smaller panel component'''
    cell_type:CellType = CellType.MONO
    quantity_row:int = 6
    quantity_col:int = 10
@dataclass
class ThermalCoef:
    """thermal behavior panel, units %/C° """
    short_circuit_t:float = 0.0814
    open_circuit_t:float = -0.3910
    power_coef_t:float = -0.5141
@dataclass
class PvConfig:
    "solar plane power technical specification"
    power:int = 100
    power_curve:PowerCurve = PowerCurve()
    cell:Cell = Cell()
    thermal:ThermalCoef = ThermalCoef()
