"""photovoltaic model component"""
from enum import Enum
from dataclasses import dataclass, field
import datetime
from geometry import GeoPosition, Orientation
from weather import Weather, WeatherParam as W
import pandas as pd
from pandas import DataFrame
from components import Component
from econometrics import Cost
import math

class CellType(Enum):
    """crystal cell configuration"""
    POLI = 'policristalino'
    MONO = 'monocristalino'

@dataclass()
class PowerCurve:
    '''voltage curve specification'''
    max_tension:float = 30.5
    short_tension:float = 37.5
    max_ampere:float = 4.26
    short_ampere:float = 5.68
@dataclass()
class Cell:
    '''smaller panel component'''
    cell_type:CellType = CellType.MONO
    quantity_row:int = 6
    quantity_col:int = 10
@dataclass()
class ThermalCoef:
    """thermal behavior panel, units %/C° """
    short_circuit_t:float = 0.0814
    open_circuit_t:float = -0.3910
    power_coef_t:float = -0.5141
@dataclass()
class PvTechnicalSheet:
    "solar plane power technical specification"
    power:int = 100
    power_curve:PowerCurve = field(default_factory=PowerCurve)
    cell:Cell = field(default_factory=Cell)
    thermal:ThermalCoef = field(default_factory=ThermalCoef)


class Photovoltaic(Component):
    """
    PV primary component
    ~~~~
    
    global component for operate Weather fetch, solar irradiation calculus, and technical
    lost. Not include shadow analysis.
    ... .normal() -> normal azimuth and elevation
    ... .cosPhi() -> angle between solar vector and normal vector
    ... .irradiation_calc() -> al irradiation received by an inclined plane
    ... .calc_energy() -> calc al lost, and irradiation performance to a nominal panel.
     
    """
    energy:DataFrame = pd.DataFrame()
    
    def __init__(
        self, description: str = 'Panel Fotovoltaico',
        model: str = 'generic',
        specification: str | None = None,
        cost: Cost = Cost(),
        quantity: int = 1,
        power:int = 100,
        orientation:Orientation = Orientation(),
        technical_sheet:PvTechnicalSheet = PvTechnicalSheet()
        ) -> None:
        super().__init__(description, model, specification, cost, quantity)
        self.power = power
        self.orientation = orientation
        self.technical_sheet = technical_sheet

    def normal(self)->dict[str,float]:
        """elevation and azimuth surface´s normal"""
        return {'azimuth':self.orientation.inclination,'elevation':self.orientation.inclination}

    def cos_phi(self,date:datetime,location:GeoPosition)->float:
        """or angle between sun and normal or surface"""
        sun= location.sun_position(date)

        cos_phi = self.orientation.cos_phi(
            sun_azimuth=sun['azimuth'],
            sun_elevation=sun['elevation'])

        return cos_phi

    def irradiation_calc(self,weather:Weather)->DataFrame:
        """calc irradiation on plane, direct,diffuse, ground and global on plane """
        irradiation:DataFrame = pd.DataFrame()
        weather_data = weather.get_data()

        irradiation['IRR_dir_plane'] = weather_data[W.DIRECT.value] * weather_data['date'].apply(
            lambda date:self.cos_phi(
                date=date,
                location=weather.geo_position))
        
        irradiation['cos_phi'] = weather_data['date'].apply(
        lambda date:self.cos_phi(
            date=date,
            location=weather.geo_position))
        
        cos_b = (1+math.cos(math.radians(self.orientation.inclination)))
        irradiation['IRR_dif_plane'] = weather_data[W.DIFFUSE.value] * 0.5 * cos_b
        irradiation['IRR_ground'] = weather_data[W.DIRECT.value] * 0.5 * weather_data[W.ALBEDO.value] * cos_b
        irradiation['IRR_global_plane'] = irradiation['IRR_dif_plane'] + irradiation['IRR_dir_plane'] + irradiation['IRR_ground']
        return irradiation

    def calc_energy(self,weather:Weather):
        """calc amount of energy generated by year"""
        #config params necessary for PV modules
        weather.parameters = [W.TEMPERATURE,W.DIRECT,W.DIFFUSE,W.ALBEDO,W.ZENITH]
        #fetch nasa weather data
        weather_data = weather.get_data()
        #tempo init values for energy
        self.energy[['date','month','day','hour']] = weather_data[['date','month','day','hour']]
        
        irr =self.irradiation_calc(weather=weather)
        self.energy = self.energy.join(irr)
        
        return self.energy
    #EOF (\n)



test_weather = Weather()
panel = Photovoltaic().calc_energy(weather=test_weather)
print(panel)